// app/layout.jsx

import React from "react";
import LayoutWrapper from "@/components/LayoutWrapper"; // Import LayoutWrapper
import localFont from "next/font/local";
import "./globals.css";

// Importing fonts
const playfair = localFont({
	src: "/fonts/PlayfairDisplayVF.ttf",
	variable: "--font-playfair-display",
	weight: "100 200 300 400 500 600 700 800 900",
});
const syncopate = localFont({
	src: "/fonts/Syncopate-Bold.ttf",
	variable: "--font-syncopate",
	weight: "400",
});

// Exporting metadata from Server Component
export const metadata = {
	title: "Chiqui Mendoza",
	description: "Generated by create next app",
};

// RootLayout as a Server Component
export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`flex h-screen overflow-hidden ${playfair.className} ${syncopate.variable} antialiased`}
			>
				<LayoutWrapper>{children}</LayoutWrapper>
			</body>
		</html>
	);
}
