// app/layout.jsx

import "./globals.css";
import Layout from "@/components/Layout";

export const metadata = {
	title: "Chiqui Mendoza",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className="flex h-full overflow-hidden">
				<Layout>{children}</Layout>
			</body>
		</html>
	);
}
