// app/layout.jsx

import React from "react";
import Sidebar from "@/components/Sidebar";
import localFont from "next/font/local";
import "./globals.css";

const playfair = localFont({
	src: "/fonts/PlayfairDisplayVF.ttf",
	variable: "--font-playfair-display",
	weight: "100 200 300 400 500 600 700 800 900",
});
const syncopate = localFont({
	src: "/fonts/Syncopate-Bold.ttf",
	variable: "--font-syncopate",
	weight: "400",
});

export const metadata = {
	title: "Chiqui Mendoza",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body
				className={`flex h-screen overflow-hidden ${playfair.className} ${syncopate.variable} antialiased`}
			>
				<Sidebar />
				<main className="flex-1 ml-96 h-full bg-zinc-50 overflow-auto">
					{children}
				</main>
			</body>
		</html>
	);
}
